export const foodList = [
  {
    id: "01",
    name: "Banofee",
    category: "Snacks",
    image: require("../assets/banofee.jpg"),
  },
  {
    id: "02",
    name: "Blue Berry Cheesecake",
    category: "Snacks",
    image: require("../assets/bbcc.jpg"),
  },
  {
    id: "03",
    name: "Chicken Sandwich",
    category: "Snacks",
    image: require("../assets/csandwich.jpg"),
  },
  {
    id: "04",
    name: "Grandpa Burger",
    category: "Snacks",
    image: require("../assets/gburger.jpg"),
  },
  {
    id: "05",
    name: "Grandpa Burger Jr.",
    category: "Snacks",
    image: require("../assets/gburgerjr.jpg"),
  },
  {
    id: "06",
    name: "Strawberry Cheesecake",
    category: "Snacks",
    image: require("../assets/scc.jpg"),
  },
  {
    id: "07",
    name: "Italian Style Carbonara",
    category: "Snacks",
    image: require("../assets/iscarbonara.jpg"),
  },
  {
    id: "08",
    name: "Special Pesto",
    category: "Snacks",
    image: require("../assets/spesto.jpg"),
  },
  {
    id: "09",
    name: "Nachos",
    category: "Snacks",
    image: require("../assets/nachos.jpg"),
  },
  {
    id: "10",
    name: "Sweet & Sour Pork",
    category: "Foods",
    image: require("../assets/sspork.jpg"),
  },
  {
    id: "11",
    name: "Smoked Pork Ribs",
    category: "Foods",
    image: require("../assets/spribs.jpg"),
  },
  {
    id: "12",
    name: "Cafe Latte",
    category: "Drinks",
    image: require("../assets/cafelatte.jpg"),
  },
  {
    id: "13",
    name: "Special Halo-Halo",
    category: "Drinks",
    image: require("../assets/halohalo.jpg"),
  },
  {
    id: "14",
    name: "Kiwi Apple Fruit Tea",
    category: "Drinks",
    image: require("../assets/kiwiapple.jpg"),
  },
  {
    id: "15",
    name: "Oreo Cheesecake",
    category: "Drinks",
    image: require("../assets/occ.jpg"),
  },
  {
    id: "16",
    name: "Passion Fruit Tea",
    category: "Drinks",
    image: require("../assets/pft.jpg"),
  },
  {
    id: "17",
    name: "Vanilla Ice Cream Latte",
    category: "Drinks",
    image: require("../assets/vicl.jpg"),
  },
];
